# Generated by Django 3.2.8 on 2021-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podCatId', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
