# Generated by Django 3.2.8 on 2021-11-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_podcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
