# Generated by Django 3.2.8 on 2021-11-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_listmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmovies',
            name='ListMoviesId',
            field=models.IntegerField(null=True),
        ),
    ]
