# Generated by Django 3.2.8 on 2021-12-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211204_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_token_RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('refreshToken', models.CharField(max_length=300)),
            ],
        ),
    ]
