# Generated by Django 3.2.8 on 2021-12-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_admin_token_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
    ]
