# Generated by Django 3.2.8 on 2021-12-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211204_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.CharField(default='NE', max_length=2),
        ),
    ]
