# Generated by Django 3.2.8 on 2021-12-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_is_admin_customuser_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category_user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
