# Generated by Django 3.2.8 on 2021-12-04 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_customuser_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='category_user',
        ),
    ]
