# Generated by Django 3.2.8 on 2021-12-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customuser_category_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_token_RefreshToken',
        ),
        migrations.AddField(
            model_name='token_refreshtoken',
            name='adminToken',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
